In [2]:
import pandas as pd 
import numpy as np

In [3]:
df = pd.read_csv(r'C:\Users\Vino Jayrasta S\OneDrive\Desktop\Dibimbing.id\DataCoSupplyChainDataset.csv', encoding='latin1')
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [4]:
df.info(verbose=True, show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [103]:
df.shape

(180519, 49)

In [6]:
df.drop(columns=['Customer Email', 'Customer Password', 'Latitude', 'Longitude', 'Product Image'], inplace=True)

In [9]:
df.drop(columns=['Order Zipcode', 'Product Description'], inplace=True)

In [10]:
df['Customer name'] = df['Customer Fname'] + ' ' + df['Customer Lname']

In [11]:
df.drop(columns=['Customer Fname', 'Customer Lname'], inplace=True)

In [13]:
df['order date (DateOrders)'] = pd.to_datetime(df['order date (DateOrders)'])

In [19]:
df['Order Year'] = df['order date (DateOrders)'].dt.year
df['Order Month'] = df['order date (DateOrders)'].dt.month
df['Order Day'] = df['order date (DateOrders)'].dt.day
df['Order Hour'] = df['order date (DateOrders)'].dt.hour

In [16]:
df['shipping date (DateOrders)'] = pd.to_datetime(df['shipping date (DateOrders)'])

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 49 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Id                    180519 non-null  int64
 12  Customer Segment               180519 non-null  object
 13  Customer State                 180519 non-null  object
 14  Customer Street                180519 non-null  object
 15  Customer Zipcode               180516 non-null  float64
 16  Department Id                  180519 non-null  int64
 17  Department Name                180519 non-null  object
 18  Market                         180519 non-null  object
 19  Order City                     180519 non-null  object
 20  Order Country                  180519 non-null  object
 21  Order Customer Id              180519 non-null  int64
 22  order date (DateOrders)        180519 non-null  datetime64[ns]
 23  Order Id                       180519 non-null  int64
 24  Order Item Cardprod Id         180519 non-null  int64
 25  Order Item Discount            180519 non-null  float64
 26  Order Item Discount Rate       180519 non-null  float64
 27  Order Item Id                  180519 non-null  int64
 28  Order Item Product Price       180519 non-null  float64
 29  Order Item Profit Ratio        180519 non-null  float64
 30  Order Item Quantity            180519 non-null  int64
 31  Sales                          180519 non-null  float64
 32  Order Item Total               180519 non-null  float64
 33  Order Profit Per Order         180519 non-null  float64
 34  Order Region                   180519 non-null  object
 35  Order State                    180519 non-null  object
 36  Order Status                   180519 non-null  object
 37  Product Card Id                180519 non-null  int64
 38  Product Category Id            180519 non-null  int64
 39  Product Name                   180519 non-null  object
 40  Product Price                  180519 non-null  float64
 41  Product Status                 180519 non-null  int64
 42  shipping date (DateOrders)     180519 non-null  datetime64[ns]
 43  Shipping Mode                  180519 non-null  object
 44  Customer name                  180511 non-null  object
 45  Order Day                      180519 non-null  int32
 46  Order Hour                     180519 non-null  int32
 47  Order Year                     180519 non-null  int32
 48  Order Month                    180519 non-null  int32
dtypes: datetime64[ns](2), float64(11), int32(4), int64(14), object(18)
memory usage: 64.7+ MB

In [21]:
df.to_csv('Dataset_setelah_cleaning.csv', index=False)

In [99]:
df[['Order Country', 'Order Region', 'Order State', 'Market']].nunique()

Order Country     164
Order Region       23
Order State      1089
Market              5
dtype: int64

In [31]:
df[['Customer Segment', 'Customer City', 'Customer Country', 'Order Profit Per Order', 'Order Item Quantity']].nunique()

Customer Segment              3
Customer City               563
Customer Country              2
Order Profit Per Order    21998
Order Item Quantity           5
dtype: int64

In [37]:
df.groupby('Market')[['Sales', 'Order Profit Per Order']].agg(['mean', 'sum', 'count'])

              Sales                      Order Profit Per Order               \
               mean           sum  count                   mean          sum
Market
Africa       197.56  2,294,452.93  11614                  21.70   252,071.18
Europe       216.36 10,872,396.80  50252                  23.27 1,169,442.96
LATAM        199.20 10,277,612.84  51594                  21.77 1,123,321.61
Pacific Asia 200.53  8,273,743.74  41260                  20.79   857,753.44
USCA         196.38  5,066,528.71  25799                  21.87   564,313.78


              count
Market
Africa        11614
Europe        50252
LATAM         51594
Pacific Asia  41260
USCA          25799

In [38]:
df.groupby('Market')[['Sales', 'Order Profit Per Order']].sum().assign(
    profit_margin_pct=lambda x: (x['Order Profit Per Order'] / x['Sales'] * 100).round(2)
)

                     Sales  Order Profit Per Order  profit_margin_pct
Market
Africa        2,294,452.93              252,071.18              10.99
Europe       10,872,396.80            1,169,442.96              10.76
LATAM        10,277,612.84            1,123,321.61              10.93
Pacific Asia  8,273,743.74              857,753.44              10.37
USCA          5,066,528.71              564,313.78              11.14

In [102]:
df.shape

(180519, 49)